### ISSUE TITLE
'Access-Control-Allow-Origin' header ist nicht definiert

### ISSUE THREAD

**Issue by Pathen85** [WAWSS16/www#1]
Du hast ja am Mittwoch bereits angedeutet, dass wir auf ein Problem stoßen werden. Ich glaube dieses Problem nun vor mir zu haben :smile: 

Und zwar bekomme ich folgende Fehlermeldung:
Der Server antwortet zunächst mit einem Error 400 'Bad Request' und sagt dann unter anderem folgendes: "No 'Access-Control-Allow-Origin' header is present on the requested resource."

Eine kurze Google-Suche hat ergeben, dass wenn eine solcher XHR Zugriff von einer fremden Domain kommt, diese Domain explizit erlaubt sein muss. Das geht indem man das sogenannte Cross-origin ressource sharing (CORS) aktiviert. Dazu muss auf dem Server in den Header der Antwort lediglich folgende Zeile eingefügt werden: "Access-Control-Allow-Origin: *"
Das sollte dann Zugriffe von allen Domains erlauben.
Siehe auch hier: http://enable-cors.org/server.html

Ich hoffe mal, dass das das von dir angesprochene Problem ist :smile:

Gruß
Henrik

**Comment by CodeKittey** [comment]
Stell dochn Pull Request, streber ;)

Ja das meinte ich.
Ich werde im Laufe des Abends es fixen, danke liebe FrontEnd Dev :)

**Comment by CodeKittey** [comment]
@Pathen85 fixed it for now, i think.
Does it work for you?

**Comment by Pathen85** [comment]
No, doesn't work. Still getting the same error.
Könnte es was bringen das hier hinzuzufügen?:

server.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

Ist von hier: http://enable-cors.org/server.html :grin:

**Comment by CodeKittey** [comment]
yeah thats exactly what 
"server.use(restify.CORS()):" does.
I tested the webserver with: And it works
http://www.test-cors.org/

Btw: Your GET Request works as well from the playerTableScript.js
But maybe you should actually send the Request.

**Comment by Pathen85** [comment]
I am still getting this when running the script "sendForm()":
"XMLHttpRequest cannot load http://139.59.134.26/api/players. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400."

I updated the GET request in playerTableScript but the readyState doesn't change..

Btw: Why are we talking English? :smile:

**Comment by CodeKittey** [comment]
Also ich weiss ja nicht was du gerade machst xD
wenn ich das einfuege:

function drawTable(address) {
	var xhr = new XMLHttpRequest();
	xhr.open('GET', address, true);

	xhr.overrideMimeType('application/json');
	var data = xhr.response;



    for (var i = 0; i < data.length; i++) {
        drawRow(data[i]);
    }

	xhr.send();
}

in dein playerTableScript.js
Dann funktioniert es.

![image](https://cloud.githubusercontent.com/assets/6086902/14942750/b770176c-0fc6-11e6-91f7-ec8c04d6a696.png)

**Comment by CodeKittey** [comment]
P.S;: because the whole internet is full of this language and github as well :p

**Comment by Pathen85** [comment]
Sehr interessant..Wenn ich das Formular mit dem Internet Explorer abschicke, bekomme ich Code 200 und Message Success, aber Chrome gibt mir immer nur die 400.. 
Der gute alte IE.. :smile:

**Comment by CodeKittey** [comment]
kann denn einer der andere die Aussage bestaetigen?
Ansonsten kannst du mal hier schaun:

http://www.html5rocks.com/en/tutorials/cors/?redirect_from_locale=de
http://stackoverflow.com/questions/24076471/xmlhttprequest-not-working
http://stackoverflow.com/questions/11330485/setting-up-cors-not-working

**Comment by Pathen85** [comment]
Also wir haben mal mit Internet Explorer, Chrome und Firefox ein bisschen rumgetestet (mit dem Code den ich heute um 19:15 Uhr committet hab) :

Internet Explorer:
1. Beim Abschicken des Formulars bekommen wir einen Code 200 als Antwort und im Header steht Message Success. Funktioniert also wie gewünscht.
2. Beim klicken auf den Button "Zeige alle Spieler" ist die Antwort vom Server wohl nicht rechtzeitig da, denn es tritt ein Fehler beim parsen der response auf.

Firefox:
1. Beim Abschicken des Formular erhalten wir einen Code 400 mit der Nachricht: "Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://139.59.134.26/api/players. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt)."
2. Das Tabellenskript funktioniert! Aber leider NUR im Debugger, wenn wir schrittweise durchgehen. Ohne Debugger tritt das gleiche Problem wie beim IE auf.

Chrome:
1. Exakt das gleiche Problem wie beim Firefox.
2. Exakt das gleiche Problem wie beim IE und beim Firefox ohne Debugger.


Also wir werden daraus nicht mehr schlau. Wir haben alle möglichen Internetseiten abgesucht und verschiedene Varianten mit onreadystatechange oder onload probiert (beim Tabellenskript jetzt), aber der einzige Weg wie die JSON Daten in unsere Variable kommen, ist per Debugger im Firefox (In den beiden anderen Browsern funktioniert es weder mit noch ohne Debugger). Das Problem scheint zu sein, dass in dem Moment wo xhr.response aufgerufen wird, der "readyState" noch nicht in 4 ist. Also dass die Daten noch nicht bereit stehen.

Bei dem anderen Problem mit dem Code 400, denke ich anhand der Fehlermeldung eher dass es am Server liegen könnte.

Wäre super, wenn du dir das nochmal anschauen könntest und versuchst die Fehlercodes zu reproduzieren :)  Ich kapiers einfach nicht :smile:

**Comment by Pathen85** [comment]
Alles gefixt..juhu! :smile: 
Der Fehler war folgender:
Wir haben beim POST den Request Header auf application/json gesetzt..Ich hatte das irgendwann mal so verstanden und dachte dass die Daten als JSON verschickt werden. Anscheinend nicht und das hat wohl dazu geführt, dass Chrome und Firefox CORS die Schuld gegeben haben.

**Comment by CodeKittey** [comment]
Oha, lol Manchmal ist es nicht immer ganz so ersichtlich und
jeder Browser macht auch noch mit dem Request selbst Voodoo 
Wenn ihr/ du morgen kommt, koennte man es sich trotzdem nochmal gemeinsam ansehen. :)

**Comment by Pathen85** [comment]
Ja sehr gerne. Ich komm auf jeden Fall!
Nochmal danke dass du die Fragestunde so kurzfristig einschieben konntest!
