### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Rahtainka** [WAWSS16/www#2]
Hi Martina @CodeKittey ,

wäre super lieb wenn du den Server an schmeißen könntest damit ich meinen Code auch mit deinem live Server testen kann.

Liebe Grüße 
Katharina

**Comment by CodeKittey** [comment]
ist up.
bleibt auch so.
Kannst du mir Feedback geben ob du auch CORS Probleme im Browser bekommst bitte? :)

**Comment by Rahtainka** [comment]
Ne, funktioniert alles. 

Bei der anderen Gruppe mittlerweile auch ^^ haben den Fehler gefunden.
